### ISSUE TITLE
Gapfilling

### ISSUE THREAD

**Issue by stineb** [computationales/FluxDataKit#10]
We need data with standardized aggregation to daily, monthly and annual values. 

- [ ]  Fill gaps, e.g., using KNN imputation (see [[here](https://bradleyboehmke.github.io/HOML/engineering.html#impute)](https://bradleyboehmke.github.io/HOML/engineering.html#impute)), record which data points are gapfilled in a QC column.

**Comment by stineb** [comment]
May adopt what @fgiardin did as described in Giardina et al. _in prep._:

`ET was gap-filled with single-layer neural networks, using temperature, PAR, VPD and ET simulated by the SPLASH model as predictors (Davis et al., 2017). To build this model, we used the R package ‘NNET’ (Venables & Ripley, 2002) and ‘CARET’ (Kuhn et al., 2021), and used a neural network with a single hidden layer, 20 nodes, 10-fold cross-validated
`

@fgiardin please coordinate with @khufkens to (possibly) adopt this

**Comment by khufkens** [comment]
Won't fix, not in line with the PLUMBER workflow - currently relying on the default plumber code.
