### ISSUE TITLE
Processing differences 

### ISSUE THREAD

**Issue by stineb** [computationales/FluxDataKit#14]
Trevor's comment on [Slack](https://lemontree-org.slack.com/archives/C027SU19GJE/p1652982810329169):
I wonder how you are integrating the Plumber2 data with the other datasets as it was processed using a different codebase with different processing decisions. The most important is likely that Plumber2 forces energy balance closure, as it is designed for land surface model evaluation, while the other datasets do not. This can lead to large differences in LE and H.

**Comment by khufkens** [comment]
Basically this is an issue / caveat that we can't address in post-processing and compositing I fear. This would require to copy the workflow of plumber. The latter is not impossible, but would require the help of original authors and access to the true underlying data if consistency is to be guaranteed.

https://github.com/aukkola/PLUMBER2

Not sure what the best approach would be.

**Comment by khufkens** [comment]
This is addressed with the new setup, recreating the plumber workflow for arbitrary fluxnet formatted data.
