### ISSUE TITLE
Citation info

### ISSUE THREAD

**Issue by stineb** [computationales/FluxDataKit#23]
For publication, we should always include a table with each eddy covariance site from which we used data and cite the appropriate paper.

I once started writing code for this in the repo [`stineb/fluxnet2015_citations`](https://github.com/stineb/fluxnet2015_citations). It contains code to create a latex table with a column with entries like `\cite{CH-Lae}`. The accompanying `.bib` file contains all bibtex entries for papers with bib-citation keys corresponding to the site names (here `CH-Lae`).

Should we provide this functionality also in FluxDataKit? If so, please adopt the code and files and note [this open issue](https://github.com/stineb/fluxnet2015_citations/issues/2#issue-1343281848).

**Comment by khufkens** [comment]
No, this pertains to the data. This is the responsibility of the user of the code upon compiling the data. We'll do this when the time comes but this has no place in the package.
