### ISSUE TITLE
Downsampling (DD)

### ISSUE THREAD

**Issue by stineb** [computationales/FluxDataKit#24]
We will need data aggregated to daily for a lot of applications (some use also for also monthly or annual). 

- Is the aggregation implemented as part of the FluxDataKit code, based on the HH data? 
- We should provide outputs also for the daily aggregated data.

**Comment by khufkens** [comment]
FluxDataKit code is HH, output for rsofun will be daily. I will not invest time in monthly unless an actual use case is presented.

**Comment by stineb** [comment]
Ok daily is enough. But we should output daily data before transferring it to rsofun forcing format. This is to keep variables that are in the FLUXNET data but not used as forcing (e.g. wind speed, ...). 

Also the remote sensing data should be offered at daily resolution, after cleaning and interpolating.

**Comment by khufkens** [comment]
This is now covered by 
https://github.com/computationales/FluxDataKit/blob/main/R/fdk_downsample_fluxnet.R

downsamples to daily data.

Equivalence on part of GPP can be checked with:
https://github.com/computationales/FluxDataKit/blob/main/analysis/02_HH_DD_flux_comparison.R

**Comment by stineb** [comment]
Script `analysis/02_HH_DD_flux_comparison.R` could not be run because the FLUXNET2015 files are not in `"data-raw/flux_data/fluxnet2015/"`. Was the intention to add them there or should they be obtained in some other way? If so, add instructions?

**Comment by khufkens** [comment]
Moved to example:

https://computationales.github.io/FluxDataKit/articles/05_qaqc_downsampled_data.html
