### ISSUE TITLE
La Thuile integration

### ISSUE THREAD

**Issue by stineb** [computationales/FluxDataKit#25]
Add La Thuile data to fdk.

**Comment by khufkens** [comment]
Data offline, but should work out of the box. Will either grab from Euler or anew if Trevor gets back to me.

**Comment by khufkens** [comment]
Quoting Dario Papale:
> the site PI of LaThuile that agreed to continue to share their data are all in FLUXNET2015. The others didn't agree to share the data longer or had big issues found later and not solved and for this reason we can not distribute them any more. My suggestion is to contact individual PIs

In  short the required effort to chase down PIs for data isn't worth our time I fear.
