### ISSUE TITLE
the unit of model gpp and EC-gpp seems not the same

### ISSUE THREAD

**Issue by lypluo** [computationales/FluxDataKit#31]
Hi Koen,

I was trying to compare the EC-based GPP from CH-Dav and p-model simulated GPP. It seems the values of EC GPP are much higher compared to modeled EC. I am wondering what's the unit of EC GPP and p-model GPP? The simulated GPP by the p-model followed the same model parameterization as Stocker et al., 2020? 

Best
![test](https://user-images.githubusercontent.com/20623298/191764538-0e65017e-88aa-4871-884e-674105eb5d01.jpg)

**Comment by stineb** [comment]
This concerns the documentation of units in arguments and outputs of the function you used to run the P-model. Is this rsofun or rpmodel?
It is all documented for rpmodel [here](https://computationales.github.io/rpmodel/reference/rpmodel.html).
For rsofun, it's not transparent enough. I'm closing this issue and raising one to clarify units in rsofun.
