### ISSUE TITLE
How to install FluxnetLSM and FluxnetEO?

### ISSUE THREAD

**Issue by stineb** [computationales/FluxDataKit#34]
The vignette `vignettes/03_data_generation.Rmd` uses the packages FluxnetLSM and FluxnetEO, but these are not dependencies of FluxDataKit. Could you add a note for how to install them (where to find them)?

**Comment by khufkens** [comment]
Added as remotes, should be installed upon package install.

https://github.com/computationales/FluxDataKit/blob/5932af9c9d4824d157ee47ac15e3cbb624b677bc/DESCRIPTION#L28
