### ISSUE TITLE
MODIS data smoothing mess

### ISSUE THREAD

**Issue by khufkens** [computationales/FluxDataKit#36]
Ok, I seriously doubt that the MODIS smoothing and gap filling routine makes any sense. Seriously f-cked up stuff IMO. Anyway, the current routine introduces spurious results throughout and in particular at year end changes, with sharp peaks in LAI/FPAR for anything that isn't northern hemisphere seasonal as far as I can tell.

**Comment by stineb** [comment]
What routine/function are you referring to? Something originally from FluxnetLSM or from ingestr?

**Comment by khufkens** [comment]
Needs pull of https://github.com/computationales/FluxDataKit/tree/modis_fix
