### ISSUE TITLE
Propagate QC flags to DD

### ISSUE THREAD

**Issue by stineb** [computationales/FluxDataKit#45]
For the DD data, specify QC information as fraction (0-1) of good (not gap-filled) HH data that went into the respective, aggregated DD data.

Keep all HH data (do not apply any filtering) and provide HH data quality in the respective QC variable. At HH, the QC variable is a code (integer, 0 = good, 1 = ...).  

This is to avoid that DD data is aggregated from HH data that has gaps. Gaps are non-random (tend to be more frequent at night). Therefore daily means calculated from cleaned, gappy, HH data will be biased.

**Comment by khufkens** [comment]
Fixed as per https://github.com/computationales/FluxDataKit/pull/47 and some commits before
