### ISSUE TITLE
Skipping file writing

### ISSUE THREAD

**Issue by stineb** [computationales/FluxDataKit#49]
Message
```
File exists, skipping
```
seems to be raised after computationally heavy calculations are executed. If file is not overwritten, all calculations may be skipped. May consider an argument `overwrite`.

**Comment by khufkens** [comment]
Which function does this refer to?

**Comment by khufkens** [comment]
removed per https://github.com/computationales/FluxDataKit/commit/ceeecadb1094ce57f4401b9320077e7b31122a90
