### ISSUE TITLE
Documentation and dissemination

### ISSUE THREAD

**Issue by stineb** [computationales/FluxDataKit#9]
### Documentation

- half-hourly, not complemented with MODIS
- daily: document how aggregated, complement daily interpolated with MODIS
- two versions:
    - 1st what we have from PLUBER, ICOS, Oneflux beta (to be done now)
    - 2nd (once provided by Ameriflux): extended site list update
- Document how much data added per site, and additional sites, compared to FLUXNET2015
- Show what additional MODIS variables added
- Explain meta info

### Dissemination

- Strategy? DOI? Data paper?
- Share with LEMONTREE

**Comment by khufkens** [comment]
Quick stats:

- 22% increase in data from 1500 to 1835 site years (without qa/qc)
- 233 sites compared to 206 (in FLUXNET2015)
- 70 "missing" sites due to incomplete data (for rsofun purposes)

Workflow is compatible with the Ameriflux data - if provided can be processed easily.

**Comment by khufkens** [comment]
Quick stats:

- 22% increase in data from 1500 to 1835 site years (without qa/qc)
- 233 sites compared to 206 (in FLUXNET2015)
- 70 "missing" sites due to incomplete data (for rsofun purposes)

Workflow is compatible with the Ameriflux data - if provided can be processed easily.

...
